version: '3'
services:
    client:
        build: .
        image: mfgryan/henclient:latest
        entrypoint: /bin/bash
        command: -c "npm run dev" 
        ports:
            - "${CLIENT_PORT:-3000}:3000"
        networks:
            - henboard
        volumes:
            - ./src:/home/nginx/src
            - node_modules:/home/nginx/node_modules
networks:
    henboard:
        external: true
volumes:
    node_modules:
