version: '3'
services:
    client:
        build: .
        image: mfgryan/henclient:latest
        entrypoint: /bin/bash
        command: -c "npm install; npm start"
        ports:
            - "${CLIENT_PORT:-3000}:3000"
        volumes:
            - ./src:/home/app/src
            - node_modules:/home/app/node_modules
volumes:
    node_modules:
