sudo: required
services: 
  - docker

language: node_js

install: true

script:
  - docker-compose -f client/docker-compose.yml build
  - docker-compose -f api/docker-compose.yml build
  - docker-compose -f docker-compose.test.yml up
  - docker-compose up -d
  - docker-compose ps

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose -f client/docker-compose.yml push
  - docker-compose -f api/docker-compose.yml push
  - echo "deploying!"
