sudo: required
services: 
  - docker

language: node_js

install: true

script:
  - docker-compose -f client/docker-compose.yml build
  - docker-compose -f api/docker-compose.yml build
  - docker-compose -f docker-compose.test.yml up
  - docker cp henboard_client_1:/home/nginx/coverage . 
  - docker-compose up -d
  - docker-compose ps
