sudo: required
services: 
  - docker

language: node_js

install: 
  - npm install coveralls

script:
  - docker-compose -f client/docker-compose.yml build
  - docker-compose -f api/docker-compose.yml build
  - docker-compose -f docker-compose.test.yml up
  - docker-compose up -d
  - docker-compose ps
