version: '2'
services:
    client:
        build: .
        image: mfgryan/henboard:latest
        container_name: henboard
        entrypoint: /bin/bash
        command: -c "npm install; npm start"
        ports:
            - 3000:3000
        volumes:
            - ./src:/home/app/src
            - node_modules:/home/app/node_modules
    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - 27017:27017
volumes:
    node_modules:
