version: '3'
services:
    client:
        image: mfgryan/henclient:latest
        entrypoint: /bin/bash
        command: -c "npm install; npm run test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js" 
        volumes:
            - client_node_modules:/home/nginx/node_modules
        environment:
            ENV: prod
            CI: "true"
volumes:
    client_node_modules:
