version: '2'
services:
    api:
        image: mfgryan/henboard:latest
        container_name: henapi
        entrypoint: /bin/bash
        command: -c "sleep infinity"
        ports:
            - 8000:8000
    client:
        image: mfgryan/henboard:latest
        container_name: henboard
        entrypoint: /bin/bash
        command: -c "npm install; npm start"
        ports:
            - 3000:3000
        volumes:
            - ./src:/home/app/src
            - node_modules:/home/app/node_modules
    db:
        image: mongo:latest
        container_name: mongo
        ports:
            - 27017:27017
volumes:
    node_modules:
