version: '3'
services:
    api:
        build:
            context: ./api
        image: mfgryan/henapi:latest
        entrypoint: /bin/bash
        command: -c "npm install; node index.js"
        ports:
            - "${API_PORT:-8080}:8080"
        volumes:
            - node_modules:/home/express/node_modules
    client:
        build:
            context: ./client
        image: mfgryan/henclient:latest
        entrypoint: /bin/bash
        command: -c "npm install; npm run build; nginx -g \"daemon off;\""
        ports:
            - "${CLIENT_PORT:-8000}:8000"
        volumes:
            - node_modules:/home/nginx/node_modules
    db:
        image: mongo:latest
        ports:
            - 27017:27017
volumes:
    node_modules:
