version: '3'
services:
    api:
        build: .
        image: mfgryan/henapi:latest
        entrypoint: /bin/bash
        command: -c "sleep infinity"
        ports:
            - "${CLIENT_PORT:-8080}:8080"
volumes:
    node_modules:
