version: '3'
services:
    api:
        build: .
        image: mfgryan/henapi:latest
        entrypoint: /bin/bash
        command: -c "npm install; node index.js"
        ports:
            - "${CLIENT_PORT:-8080}:8080"
        volumes:
            - node_modules:/home/express/node_modules
volumes:
    node_modules:
