version: '3'
services:
    api:
        build: .
        image: mfgryan/henapi:latest
        entrypoint: /bin/bash
        command: -c "npm run dev"
        ports:
            - "${CLIENT_PORT:-3001}:3001"
        networks:
            - henboard
        volumes:
            - node_modules:/home/express/node_modules
            - ./:/home/express
networks:
    henboard:
        external: true
volumes:
    node_modules:
