version: '3'
services:
    api:
        build: .
        image: mfgryan/henapi:latest
        entrypoint: /bin/bash
        command: -c "npm run dev"
        ports:
            - "${CLIENT_PORT:-8080}:8080"
        volumes:
            - node_modules:/home/express/node_modules
            - ./:/home/express
volumes:
    node_modules:
